server:
  servlet:
    context-path: /springboot5zy

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase?userUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hr.springboot5zy.entity